checks:
  services:
    enabled: true
    items:
      - docker
      - ssh
  docker_containers:
    enabled: true
    expected:
      - logos-frontend-main
      - logos-backend-main
      - logos-frontend-dev
      - logos-backend-dev
