checks:
  services:
    enabled: false
    items:
      - docker
      - ssh
  system_resources:
    enabled: false

    uptime:
      enabled: true

    load:
      enabled: true

    memory:
      enabled: true

    disk:
      enabled: true
      warning_percent: 80
      critical_percent: 90
      paths:
        - /

  docker_containers:
    enabled: false
    expected:
      - example-frontend
      - example-backend
  k3s:
    enabled: false
    token:
      enabled: false
      path: /var/lib/rancher/k3s/server/token
      backup_path: /var/backups/krowa-admin/k3s-token.bak
    namespaces:
      enabled: true
      system:
        - default
        - kube-system
        - kube-public
        - kube-node-lease
        - metallb-system
